# Generated by Django 2.0.4 on 2018-05-25 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='ci',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid format for CI, must be just numbers of your CI, and must be ALIVE!', regex='[0-9]{7,10}')]),
        ),
    ]
