# Generated by Django 2.0.4 on 2018-06-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180525_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profileImage',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
