# Generated by Django 2.0.4 on 2018-05-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20180519_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MakingProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('difficult', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('referenceInput', models.FileField(upload_to='uploads/')),
                ('referenceOutput', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('referenceContent', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='makingproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Problem'),
        ),
        migrations.AddField(
            model_name='makingproblem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student'),
        ),
        migrations.AddField(
            model_name='learningtheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Theme'),
        ),
        migrations.AlterUniqueTogether(
            name='learningtheme',
            unique_together={('student', 'theme')},
        ),
    ]
