# Generated by Django 2.0.4 on 2018-05-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='progress',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
