# Generated by Django 2.0.4 on 2018-06-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtheme',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
