# Generated by Django 2.0.4 on 2018-05-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180525_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacherMentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
    ]
