# Generated by Django 2.0.4 on 2018-06-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180621_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
