# Generated by Django 2.0.4 on 2018-06-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_theme_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='referenceInput',
        ),
    ]
