# Generated by Django 2.0.4 on 2018-06-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_problem_referenceinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficult',
        ),
        migrations.RemoveField(
            model_name='student',
            name='progress',
        ),
        migrations.AddField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='progress',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Theme'),
        ),
        migrations.AddField(
            model_name='difficult',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Problem'),
        ),
        migrations.AddField(
            model_name='difficult',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Theme'),
        ),
    ]
