# Generated by Django 2.0.4 on 2018-06-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180622_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='referenceInput',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
