# Generated by Django 2.0.4 on 2018-06-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180622_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='referenceOutput',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
