# Generated by Django 2.0.4 on 2018-06-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180622_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
