# Generated by Django 2.0.4 on 2018-06-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180622_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='makingproblem',
            name='compile_tries',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
