# Generated by Django 2.0.4 on 2018-06-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_theme_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='index',
        ),
    ]
