# Generated by Django 2.0.4 on 2018-06-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_theme_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtheme',
            name='IsDisabled',
            field=models.BooleanField(default=True),
        ),
    ]
