# Generated by Django 2.0.4 on 2018-06-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20180624_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtheme',
            name='IsDisabled',
        ),
    ]
