# Generated by Django 2.0.4 on 2018-06-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_learningtheme_isdisabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtheme',
            name='IsDisabled',
            field=models.BooleanField(default=False),
        ),
    ]
