# Generated by Django 2.0.4 on 2018-06-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_learningtheme_isdisabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningtheme',
            old_name='IsDisabled',
            new_name='IsEnabled',
        ),
    ]
