# Generated by Django 2.0.4 on 2018-06-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20180624_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtheme',
            name='IsEnabled',
        ),
        migrations.AddField(
            model_name='learningtheme',
            name='IsDisabled',
            field=models.BooleanField(default=True),
        ),
    ]
