# Generated by Django 2.0.4 on 2018-06-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_makingproblem_compile_tries'),
        ('student', '0017_auto_20180624_0246'),
    ]

    operations = [
    ]
