# Generated by Django 2.0.4 on 2018-06-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_merge_20180624_1033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='difficult',
            unique_together={('problem', 'theme')},
        ),
        migrations.RemoveField(
            model_name='makingproblem',
            name='compile_tries',
        ),
        migrations.AlterUniqueTogether(
            name='makingproblem',
            unique_together={('student', 'problem')},
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('student', 'theme')},
        ),
    ]
