# Generated by Django 2.0.4 on 2018-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20180624_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtheme',
            name='IsDisabled',
        ),
        migrations.AddField(
            model_name='theme',
            name='IsDisabled',
            field=models.BooleanField(default=True),
        ),
    ]
