# Generated by Django 2.0.4 on 2018-06-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20180624_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtheme',
            name='IsDisabled',
            field=models.BooleanField(default=True),
        ),
    ]
