# Generated by Django 2.0.4 on 2018-06-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_learningtheme_isdisabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
